AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Word of the Day API

Globals:
  Function:
    Runtime: java21
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        AWS_DYNAMODB_ENDPOINT_OVERRIDE: ""
        aws.region: eu-west-1
        MICRONAUT_ENVIRONMENTS: dev

Resources:
  WordOfDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.marszalek.FunctionRequestHandler
      CodeUri: target/word-of-the-day-0.1.jar
      Events:
        GetWord:
          Type: Api
          Properties:
            Path: /api/v1/word/today
            Method: get
        PostGuess:
          Type: Api
          Properties:
            Path: /api/v1/word/guess
            Method: post