AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Word of the Day API - JVM

Parameters:
  RedisUri:
    Type: String
    NoEcho: true
  ApiNinjasKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: java21
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        MICRONAUT_ENVIRONMENTS: prod
        REDIS_URI: !Ref RedisUri
        API_NINJAS_KEY: !Ref ApiNinjasKey

Resources:
  WordOfDaySchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.marszalek.SchedulerHandler
      CodeUri: target/word-of-the-day-0.1.jar
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: word-of-the-day
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)
            Name: word-of-the-day-scheduler
            Description: Fetches and stores word of the day at 9am UTC
            Enabled: true