AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Word of the Day API - Native Image

Parameters:
  RedisUri:
    Type: String
    NoEcho: true
  ApiNinjasKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        MICRONAUT_ENVIRONMENTS: prod
        REDIS_URI: !Ref RedisUri
        API_NINJAS_KEY: !Ref ApiNinjasKey

Resources:
  WordOfDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.marszalek.FunctionRequestHandler
      CodeUri: target/function.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: word-of-the-day
      Events:
        GetWord:
          Type: Api
          Properties:
            Path: /api/v1/word/today
            Method: get
        GetWordOptions:
          Type: Api
          Properties:
            Path: /api/v1/word/today
            Method: options
        PostGuess:
          Type: Api
          Properties:
            Path: /api/v1/word/guess
            Method: post
        PostGuessOptions:
          Type: Api
          Properties:
            Path: /api/v1/word/guess
            Method: options

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"