micronaut.application.name=word-of-the-day
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins=*
micronaut.server.cors.configurations.web.allowed-methods=GET,POST,OPTIONS
micronaut.server.cors.configurations.web.allowed-headers=Content-Type,Accept

aws.dynamodb.endpoint-override=
aws.region=eu-west-1

api.ninjas.key=${API_NINJAS_KEY}